name: "deploy to dev"

on:
  pull_request:
    types: [ closed ]
    branches: [ dev ]

env:
  IMAGE_NAME: api

concurrency:
  group: ci-deploy-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions: # Necessary for workload identity provider
      contents: 'read'
      id-token: 'write'
    
    if: github.event.pull_request.merged == true
    steps:
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: '${{ secrets.PROJECT_ID }}'
          token_format: access_token
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'
      
      - name: Deploy to Google Cloud Functions
        run: firebase deploy --only functions --project ${{ secrets.PROJECT_ID }}