name: "deploy to dev"

on:
  pull_request:
    types: [ closed ]
    branches: [ dev ]

concurrency:
  group: ci-deploy-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions: # Necessary for workload identity provider
      contents: 'read'
      id-token: 'write'
    
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout Repo
      uses: 'actions/checkout@v4'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Installing dependencies
      run: |
        npm install
        npm install -g firebase-tools
        cd functions && npm install

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: '${{ secrets.PROJECT_ID }}'
        token_format: access_token
        workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.SERVICE_ACCOUNT }}'
    
    - name: Deploy to Google Cloud Functions
      run: firebase deploy --only functions --project ${{ secrets.PROJECT_ID }}